<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.3" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.3" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.1.3" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.1.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <!-- Referencia al Worker para Host Embedding -->
    <ProjectReference Include="..\AzureDevOps.IngestionWorker\AzureDevOps.IngestionWorker.csproj" />
  </ItemGroup>
</Project>
